import turtle
pen = turtle. Turtle()
paper = turtle. Screen()

paper. bgcolor('white')
pen.speed(5)

#body
pen.fillcolor("black")
pen.up()
pen.goto(-60,-55)
pen.down()
pen.begin_fill()
pen.circle(100)
pen.end_fill()
pen.up()

#triangle
pen.fillcolor('yellow')
pen.goto(0,0)
pen.begin_fill()
pen.goto(50,100)
pen.left(180)
pen.forward(100)
pen.goto(0,0)
pen.end_fill()
pen.up()

#eyes
pen.goto(-10,80)
pen.fillcolor('black')
pen.begin_fill()
pen.circle(3)
pen.end_fill()
pen.goto(10,80)
pen.fillcolor('black')
pen.begin_fill()
pen.circle(3)
pen.end_fill()


#mouth
pen.fillcolor('black')
pen.goto(-10,60)
pen.begin_fill()
pen.down()
pen.goto(10,60)
pen.goto(10,30)
pen.goto(0,20)
pen.goto(-10,30)
pen.goto(-10,60)
pen.end_fill()
#teeth
pen.fillcolor('white')
pen.begin_fill()
pen.goto(-9,58)
pen.right(180)
pen.forward(18)
pen.right(90)
pen.forward(4)
pen.right(90)
pen.forward(18)
pen.right(90)
pen.forward(4)
pen.end_fill()
pen.up()

#octogon
pen.goto(-150,120)
pen.right(45)
pen.fillcolor('firebrick')
pen.begin_fill()
for i in range (8):
  pen.right(45)
  pen.forward(50)
pen.end_fill()

#eyes
pen.goto(-135,85)
pen.fillcolor('black')
pen.begin_fill()
pen.circle(4)
pen.end_fill()
pen.goto(-105,85)
pen.fillcolor('black')
pen.begin_fill()
pen.circle(4)
pen.end_fill()

#mouth
pen.goto(-120,50)
pen.down()
pen.fillcolor('black')
pen.begin_fill()
pen.right(90)
pen.forward(20)
pen.right(30)
pen.forward(30)
pen.right(105)
pen.forward(50)
pen.right(105)
pen.forward(30)
pen.right(30)
pen.forward(20)
pen.end_fill()
pen.up()
#teeth
pen.right(45)
pen.goto(-140,10)
pen.fillcolor('white')
pen.begin_fill()
pen.forward(37)
pen.left(90)
pen.forward(4)
pen.left(90)
pen.forward(37)
pen.left(90)
pen.forward(4)
pen.end_fill()
pen.up()
turtle.done()
